# Theme: default, hacky, bloody, solarized_dark, solarized_light
theme = "default"

# Comma-separated hardware acceleration options to ignore.
# Possible values: nvidia, intel, amd, vaapi, macos
hide_hwaccel_options = ""
