background = "16"
background_highlight = "22"
accent = "46"
accent_light = "83"
border_active = "40"
border_inactive = "22"
list_highlight = "46"
list_highlight_text = "16"
text = "40"
text_input = "83"
text_muted = "22"
text_param = "83"
text_param_disabled = "22"
keys = "46"
info = "34"
info_text = "28"
warning = "119"
warning_text = "35"
error = "52"
error_text = "46"
color1 = "46"
color2 = "28"
color3 = "83"
