background = "#fdf6e3"
background_highlight = "#eee8d5"
accent = "#859900"
accent_light = "#cb4b16"
border_active = "#073642"
border_inactive = "#93a1a1"
list_highlight = "#859900"
list_highlight_text = "#002b36"
text = "#657b83"
text_input = "#073642"
text_muted = "#93a1a1"
text_param = "#2aa198"
text_param_disabled = "#93a1a1"
keys = "#859900"
info = "#268bd2"
info_text = "#657b83"
warning = "#b58900"
warning_text = "#657b83"
error = "#dc322f"
error_text = "#fdf6e3"
color1 = "#cb4b16"
color2 = "#2aa198"
color3 = "#d33682"
