background = "16"
background_highlight = "88"
accent = "196"
accent_light = "210"
border_active = "196"
border_inactive = "124"
list_highlight = "196"
list_highlight_text = "16"
text = "196"
text_input = "210"
text_muted = "124"
text_param = "210"
text_param_disabled = "124"
keys = "196"
info = "160"
info_text = "124"
warning = "216"
warning_text = "160"
error = "203"
error_text = "16"
color1 = "196"
color2 = "160"
color3 = "210"
