background = "#002b36"
background_highlight = "#073642"
accent = "#859900"
accent_light = "#cb4b16"
border_active = "#859900"
border_inactive = "#586e75"
list_highlight = "#859900"
list_highlight_text = "#002b36"
text = "#839496"
text_input = "#eee8d5"
text_muted = "#586e75"
text_param = "#2aa198"
text_param_disabled = "#586e75"
keys = "#859900"
info = "#268bd2"
info_text = "#839496"
warning = "#b58900"
warning_text = "#839496"
error = "#dc322f"
error_text = "#eee8d5"
color1 = "#cb4b16"
color2 = "#2aa198"
color3 = "#d33682"
