background = "reset"
background_highlight = "dark-gray"
accent = "blue"
accent_light = "light-blue"
border_active = "white"
border_inactive = "dark-gray"
list_highlight = "white"
list_highlight_text = "black"
text = "white"
text_input = "white"
text_muted = "gray"
text_param = "yellow"
text_param_disabled = "dark-gray"
keys = "green"
info = "blue"
info_text = "white"
warning = "yellow"
warning_text = "white"
error = "red"
error_text = "white"
color1 = "light-yellow"
color2 = "light-cyan"
color3 = "light-magenta"
