background = "#001400"
background_highlight = "#003200"
accent = "#00ff00"
accent_light = "#64ff64"
border_active = "#00c800"
border_inactive = "#005000"
list_highlight = "#00ff00"
list_highlight_text = "black"
text = "#00c800"
text_input = "#32ff32"
text_muted = "#006400"
text_param = "#64ff64"
text_param_disabled = "#005000"
keys = "#00ff00"
info = "#00b400"
info_text = "black"
warning = "#96ff32"
warning_text = "black"
error = "#c83232"
error_text = "black"
color1 = "#00ff00"
color2 = "#009600"
color3 = "#32c832"
